kind: Pod
apiVersion: v1
metadata:
        name: testpod6
        labels:
                env: development
                class: pods
spec:
        containers:
                - name: c00
                  image: ubuntu
                  command: ["/bin/bash", "-c", "while true; do echo Hello-Siddharth; sleep 5 ; done"]

     
