kind: Pod
apiVersion: v1
metadata:
        name: testpod2
        annotations:
                description: this is sample annotation
spec:
        containers:
                - name: c00
                  image: ubuntu
                  command: ["/bin/bash", "-c", "while true; do echo Hello-Siddharth; sleep 5 ; done"]
        restartPolicy: Never      # Defaults to Always
