kind: Deployment
apiVersion: apps/v1
metadata:
        name: testdeploy
spec:
        replicas: 3
        selector:
                matchLabels:
                        env: prod
        template:
                metadata:
                        name: testpod
                        labels:
                                env: prod
                spec:
                        containers:
                                - name: testc
                                  image: httpd
                                  ports:
                                          - containerPort: 80
