kind: Service                             
apiVersion: v1
metadata:
  name: testservice
spec:
  ports:
    - port: 80                          
      targetPort: 80                    
  selector:
          env: prod                   
  type: ClusterIP                       
