apiVersion: batch/v1
kind: CronJob
metadata:
  name: mycronjob
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - image: ubuntu
            name: mycronjob
            command: ["/bin/bash","-c","sleep 10"]
          restartPolicy: Never
  schedule: '* * * * *'
