---
kind: Namespace
apiVersion: v1
metadata:
        name: nidhins
---
apiVersion: batch/v1
kind: Job
metadata:
  name: myjob
  namespace: nidhins
spec:
  completions: 10
  parallelism: 3
  activeDeadlineSeconds: 30  
  template:
    spec:
      containers:
      - image: ubuntu
        name: myjob
        command: ["/bin/bash","-c","sleep 10"]
      restartPolicy: Never
